### PR TITLE
feat: link new beleidsvelden to all agenda's of this year

### PR DESCRIPTION
**Pull request by sergiofenoll**
https://kanselarij.atlassian.net/browse/KAS-4613

On agenda's of this year (2024) and all related data points, replace links to the now invalidated government fields to the new ones.

### CODE REVIEW

**Review by ValenberghsSven — COMMENTED** [review]
field `bc15da36-a7a3-46eb-9af6-d6a8a12b0ad1` or "Landbouw- en zeevisserijonderzoek'" 
has been invalidated but it has been used in 2024 according to queries.
We have not attached a replacement field in this query

52 fields were generated
53 fields were invalidated
The query only has 52 values of field replacements.
Should we replace this with the new field for "Landbouw- en zeevisserij" ?

**Comment by sergiofenoll** [comment]
> field `bc15da36-a7a3-46eb-9af6-d6a8a12b0ad1` or "Landbouw- en zeevisserijonderzoek'" has been invalidated but it has been used in 2024 according to queries. We have not attached a replacement field in this query
> 
> 52 fields were generated 53 fields were invalidated The query only has 52 values of field replacements. Should we replace this with the new field for "Landbouw- en zeevisserij" ?

This was an oversight. But there's no new "Landbouw- en zeevisserijonderzoek" field. Do we add the old ones to "Landbouw en zeevisserij"?

**Comment by ValenberghsSven** [comment]
> > field `bc15da36-a7a3-46eb-9af6-d6a8a12b0ad1` or "Landbouw- en zeevisserijonderzoek'" has been invalidated but it has been used in 2024 according to queries. We have not attached a replacement field in this query
> > 52 fields were generated 53 fields were invalidated The query only has 52 values of field replacements. Should we replace this with the new field for "Landbouw- en zeevisserij" ?
> 
> This was an oversight. But there's no new "Landbouw- en zeevisserijonderzoek" field. Do we add the old ones to "Landbouw en zeevisserij"?

We are probably better off checking with the users

**Comment by ValenberghsSven** [comment]
On second look, there is only 1 subcase and its decisionmaking flow that has that field connected.

image
It already has that alternate field "Landbouw en Zeevisserij"
So if we include in our migration that we map the old "onderzoek" also to "Landbouw en Zeevisserij" it should be fine? no user input required

**Review by ValenberghsSven — APPROVED** [review]

**Pull request merged**
