### PR TITLE
add service in docker-compose and modify dispatcher for new requests

### PR DESCRIPTION
**Pull request by StuyckRuben**
https://kanselarij.atlassian.net/browse/KAS-3939

- [ ] Merge https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1799
- [ ] Merge https://github.com/kanselarij-vlaanderen/file-bundling-service/pull/13

### CODE REVIEW

**Review by sergiofenoll — CHANGES_REQUESTED** [review]
You'll want to undo these changes and instead add the following:

```diff
   file-bundling:
     image: kanselarij/file-bundling-service:2.2.1
+    environment:
+      MU_APPLICATION_FILE_STORAGE_PATH: "generated-archives/"
     volumes:
       - ./data/files:/share
-      - ./data/generated-archives:/archive
     logging: *default-logging
     restart: always
```

This ensures that the file-bundling service will write its archive files to the `generated-archives` subdirectory.

Additionally, create this directory inside `data/files/` and add a dummy file (e.g. an emtpy `.gitkeep` file) so that we track it in our VCS. You should end up with `data/files/generated-archives/.gitkeep`, which is an empty file.

**Comment by ValenberghsSven** [comment]
> You'll want to undo these changes and instead add the following:
> 
> ```diff
>    file-bundling:
>      image: kanselarij/file-bundling-service:2.2.1
> +    environment:
> +      MU_APPLICATION_FILE_STORAGE_PATH: "generated-archives/"
>      volumes:
>        - ./data/files:/share
> -      - ./data/generated-archives:/archive
>      logging: *default-logging
>      restart: always
> ```
> 
> This ensures that the file-bundling service will write its archive files to the `generated-archives` subdirectory.
> 
> Additionally, create this directory inside `data/files/` and add a dummy file (e.g. an emtpy `.gitkeep` file) so that we track it in our VCS. You should end up with `data/files/generated-archives/.gitkeep`, which is an empty file.

done

**Review by sergiofenoll — APPROVED** [review]

**Comment by sergiofenoll** [comment]
Changes to `testdata.zip` are expected, right?

**Comment by ValenberghsSven** [comment]
> Changes to `testdata.zip` are expected, right?

It also needed a new folder "generated-archives" in the files folder for future tests.

**Pull request merged**
