### PR TITLE
KAS-3658: Source file as main file

### PR DESCRIPTION
**Pull request by sergiofenoll**
- Make existing source files be the "main" file of a piece
- Replace the predicate between piece and file
  - Update Elastic config to find files
- Rename relations between file and derived (now `source` and `derived` instead of `primarySource` and `primarySourceOf`
- `testdata.zip` contains Piece with a file that has a derived file. First uploaded using the old version (so file + source file), then after migrations ran it was correctly set as source file + derived file. (This was my best attempt at showcasing the the main migration of this story actually works and is kind-of testable)

### CODE REVIEW

**Comment by ValenberghsSven** [comment]
@sergiofenoll 
As for the `testdata.zip` file, I was about to merge a  `testdata.zip` with a whole new setup (2 agendas with subcases) for a cypress ticket. I did not know (or check) that someone else was changing the zip file.
So your zipfile should not be merged as that will not work without losing that entire setup.

I could add some source/derived files to current agendaitems or publications and update my zip.
In any case, as long as this ticket is still open, there is still time to change the zip on development after my merge, just let me know.

**Comment by sergiofenoll** [comment]
> @sergiofenoll 
> As for the `testdata.zip` file, I was about to merge a  `testdata.zip` with a whole new setup (2 agendas with subcases) for a cypress ticket. I did not know (or check) that someone else was changing the zip file.
> So your zipfile should not be merged as that will not work without losing that entire setup.
> 
> I could add some source/derived files to current agendaitems or publications and update my zip.
> In any case, as long as this ticket is still open, there is still time to change the zip on development after my merge, just let me know.

If you can add a file + a "source" file to your zip that would be great, then I'll discard the changes to the zip in this PR. Otherwise, I'll merge dev back into here and add one myself.

**Comment by erikap** [comment]
Services to bump before merging this PR:
- [x] https://github.com/kanselarij-vlaanderen/yggdrasil/pull/49
- [x] https://github.com/kanselarij-vlaanderen/file-bundling-job-creation-service/pull/3

**Comment by ValenberghsSven** [comment]
added 11 source files to testdata.zip in my PR.
Will update when that PR is merged, just make sure to accept the incoming zip.
In any case, I got backups locally

**Comment by ValenberghsSven** [comment]
> added 11 source files to testdata.zip in my PR. Will update when that PR is merged, just make sure to accept the incoming zip. In any case, I got backups locally

my zip got merged.
You should find docs with sourcefiles on 22/04/2022 and 23/04/2022 agendas (1 open, 1 closed + fully released docs)

**Pull request merged**
