### PR TITLE
Feature/kas 2733 virtuoso upgrade

### PR DESCRIPTION
**Pull request by MikiDi**
Main reason for this upgrade is to have the memory-leak fixes included within v7.2.6.
This RPIO image will soon have support for [maintenance-related mu-scripts ](https://github.com/redpencilio/docker-virtuoso/pull/5) which is even better.
Tests running in http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/145/

May be merged as soon as @ValenberghsSven is ok with how the tests turn out.

### CODE REVIEW

**Review by ValenberghsSven — APPROVED** [review]
Tests succeeded, so guess it's ok.

**Comment by ValenberghsSven** [comment]
I assumed a successful test run was enough, but the ticket mentions migrations may be needed.
Is this not the case or are they just not included?

**Comment by MikiDi** [comment]
"Migratie" was misschien een ongelukkig gekozen verwoording. De interne database-structuur wordt bij upgrade door Virtuoso automatisch aangepast (je transaction file moet leeg zijn). Dat heb ik voor de test-dataset (zip) ook uitgevoerd. Een waarschuwing voor de devs hun lokale setup staat hier https://chat.semte.ch/group/kanselarij-dev?msg=n24Q7hNwBCvvZ68Rf

**Comment by ValenberghsSven** [comment]
@MikiDi Merge at your own convenience. Any deploy (DEV, ACC, PROD) should be done with caution (backup etc?)
Will you take on that task?

**Pull request merged**
