### PR TITLE
feat: add migrations for new beleidsvelden

### PR DESCRIPTION
**Pull request by sergiofenoll**
https://kanselarij.atlassian.net/browse/KAS-4585

Adds the new beleidsdomeinen and -velden to Kaleidos. 

Themis PR: https://github.com/kanselarij-vlaanderen/app-themis/pull/21

### CODE REVIEW

**Comment by ValenberghsSven** [comment]
is this normal:
image

**Comment by tdn** [comment]
Looks fine, but since we have a massive release already, I'd be inclined to wait until we've pushed the current tickets on acceptance to production. Testing will be easier and more self-contained then.

**Comment by ValenberghsSven** [comment]
FYI, some cypress tests are using the old domains (ofc it's exactly the ones we need to change) so tests will fail on them. Will try to fix these either before or after merge

**Comment by ValenberghsSven** [comment]
Starting a frontend branch to fix the tests that are still using the old domains and fields

**Review by ValenberghsSven — APPROVED** [review]
I have run this migration locally and it looks ok.
Inspected some data and it all seems to be there.
Wait for cypress testes are updated before merging

**Comment by ValenberghsSven** [comment]
also, before merge we should rename the files to a later date. To keep the migrations on PROD chronologically correct

**Pull request merged**
