### PR TITLE
removed unused procedurestaptypes and replaced example URI with themi…

### PR DESCRIPTION
**Pull request by StuyckRuben**
@ValenberghsSven You asked me to tag you on this regarding the tests.

### CODE REVIEW

**Review by tdn — APPROVED** [review]
Looked at it together, and this works locally. See no reason this wouldn't work on DEV or ACCEPT

@ValenberghsSven at some points, the testdata should ideally be updated to include some of the remaining types. Currently only one is being used it seems ("in voorbereiding").

**Comment by ValenberghsSven** [comment]
> Looked at it together, and this works locally. See no reason this wouldn't work on DEV or ACCEPT
> 
> @ValenberghsSven at some points, the testdata should ideally be updated to include some of the remaining types. Currently only one is being used it seems ("in voorbereiding").

I will replace all the "in voorbereiding" in frontend with a paired frontend branch

**Review by ValenberghsSven — APPROVED** [review]
Tests changed, jenkins green on frontend PR.

**Comment by ValenberghsSven** [comment]
the `dct:type` select query results on ACC:
image

**Pull request merged**
