### PR TITLE
added mixdossier migrations. 

### PR DESCRIPTION
**Pull request by tdn**
Locally, some cases are still missed, so will need follow-up.

### CODE REVIEW

**Review by tdn — COMMENTED** [review]
Heb nog verscheidene kleine bugs en foutjes ontdekt in m'n code om de migraties aan te maken. Maakte o.a. te veel DELETEs aan, wat niet ideaal is. Ik ga ze nu nog even laten re-genereren en opnieuw testen.

**Review by erikap — APPROVED** [review]
Looks good :+1: 

:warning:  We're not going to merge this branch in the Git repos, since the migrations are environment specific, but copy and execute them directly on the test server.

**Comment by ValenberghsSven** [comment]
> Looks good +1
> 
> warning We're not going to merge this branch in the Git repos, since the migrations are environment specific, but copy and execute them directly on the test server.

If this is not mergable, perhaps mark it as draft to avoid accidental merging?

**Comment by erikap** [comment]
@tdn This one can be closed since migrations are executed on PROD?

**Comment by ValenberghsSven** [comment]
@tdn can this old branch be deleted or do you want to keep it for any reason?

**Pull request closed without merging**
